global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["application:8000"]

    relabel_configs:
      - target_label: application
        replacement: "application"
